import{a as y,i as E,S as w,R as M}from"./assets/vendor-CsQmPkTk.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const B=({_id:e,strArtist:t,strArtistThumb:n,genres:s,strBiographyEN:o})=>`
<li class="artist-card">
  <img src="${n}" alt="${t}" class="artist-photo" />
  <ul class="artist-genres">
    ${s.map(r=>`<li class="genre-tag">${r}</li>`).join("")}
  </ul>
  <h3 class="artist-name">${t}</h3>
  <p class="artist-info">${o}</p>
 <button class="learn-more-btn" data-artist-id="${e}">Learn More</button>
</li>
`;function L(e,t){if(!e||!e.length)return;const n=e.map(s=>B(s)).join("");t.insertAdjacentHTML("beforeend",n)}function k(e){e.classList.remove("hidden")}function h(e){e.classList.add("hidden")}y.defaults.baseURL="https://sound-wave.b.goit.study/api/";async function v(e,t){try{return(await y.get("/artists",{params:{limit:t,page:e}})).data}catch(n){return console.error(n),{artists:[],totalArtists:0}}}const m=8;let u=1;const c={cardsContainer:document.querySelector("#cards-container"),loadMoreBtn:document.querySelector(".loadMoreBtn")};async function S(){const{artists:e,totalArtists:t}=await v(u,m);L(e,c.cardsContainer),u*m<t?k(c.loadMoreBtn):h(c.loadMoreBtn)}S();async function b(){u++;try{const{artists:e,totalArtists:t,page:n}=await v(u,m);L(e,c.cardsContainer);const s=Math.ceil(t/m);u>=s&&(E.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:4e3,titleColor:"#fff",backgroundColor:" #09f",messageColor:"#fff"}),h(c.loadMoreBtn),c.loadMoreBtn.removeEventListener("click",b))}catch(e){console.log(e)}}c.loadMoreBtn.addEventListener("click",b);let i;async function A(){const e=await fetch("https://sound-wave.b.goit.study/api/feedbacks");if(!e.ok)throw new Error("Помилка завантаження");const t=await e.json();return console.log("Отримані відгуки:",t),t.data}function I(e){const t=document.getElementById("feedback-list");t.innerHTML="",e.forEach(({id:n,name:s,descr:o,rating:r})=>{const a=document.createElement("div");a.classList.add("swiper-slide"),a.dataset.id=n,a.innerHTML=`
        <div class="feedback-card">
            <h4>${s}</h4>
            <p>${o}</p>
            <div class="star-rating" data-rating="${Math.round(r)}"></div>
        </div>`,t.appendChild(a)})}function T(){document.querySelectorAll(".star-rating").forEach(t=>{const n=parseInt(t.dataset.rating,10);M({element:t,readOnly:!0,score:n,starType:"svg",starSize:20,hints:[]})})}function g(e,t){const n=document.getElementById("pagination-first"),s=document.getElementById("pagination-middle"),o=document.getElementById("pagination-last");n.classList.remove("active"),s.classList.remove("active"),o.classList.remove("active"),e===0?n.classList.add("active"):e===t-1?o.classList.add("active"):s.classList.add("active")}function q(e){i&&i.destroy(!0,!0),i=new w(".feedback-swiper",{navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},slidesPerView:1,spaceBetween:20,loop:!1}),i.on("slideChange",()=>{g(i.activeIndex,e)}),g(i.activeIndex,e),document.getElementById("pagination-first").onclick=()=>i.slideTo(0),document.getElementById("pagination-last").onclick=()=>i.slideTo(e-1),document.getElementById("pagination-middle").onclick=()=>{e>2&&i.slideTo(1)},T()}document.addEventListener("DOMContentLoaded",()=>{A().then(e=>{I(e),q(e.length)}).catch(e=>console.error(e))});const l=document.getElementById("artist-modal"),f=l.querySelector(".modal-content"),C=l.querySelector(".close-btn");async function $(e){try{document.body.classList.add("no-scroll"),l.classList.remove("is-hidden"),f.innerHTML='<span class="loader">Loading...</span>';const t=await fetch(`https://sound-wave.b.goit.study/api/artists/${e}`);if(!t.ok)throw new Error("Failed to fetch artist details");const n=await t.json();f.innerHTML=generateArtistMarkup(n)}catch{f.innerHTML="<p>Error loading artist data.</p>"}}function p(){l.classList.add("is-hidden"),document.body.classList.remove("no-scroll"),f.innerHTML=""}C.addEventListener("click",p);l.addEventListener("click",e=>{e.target===l&&p()});document.addEventListener("keydown",e=>{e.key==="Escape"&&p()});document.querySelector(".gallery").addEventListener("click",e=>{if(e.target.closest(".learn-more-btn")){const n=e.target.closest(".artist-card").dataset.id;$(n)}});document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".burger-btn"),t=document.querySelector(".mobile-menu"),n=document.querySelector(".mobile-close"),s=document.querySelector(".mobile-backdrop"),o=document.querySelector(".header-logo-link");let r=!1;const a=()=>{s.classList.remove("open"),t.classList.remove("open"),document.body.style.overflow=""};e.addEventListener("click",()=>{if(s.classList.add("open"),t.classList.add("open"),document.body.style.overflow="hidden",!r&&o){const d=o.cloneNode(!0);d.classList.add("mobile-logo"),t.prepend(d),r=!0}}),n.addEventListener("click",a),s.addEventListener("click",d=>{d.target===s&&a()}),t.querySelectorAll("a").forEach(d=>{d.addEventListener("click",a)})});
//# sourceMappingURL=index.js.map
